# RainBot on Canternet

# Server information
host : irc.canternet.org
port : 6667

# Channel Information
channels :
  - "#snowybottest"

# User information
nick       : RainBot
realname   : PinkDawn's Unstable Bot
username   : RainBotDev
modes      : +B

# Command Information
commandprefix : ";"

# Modules
modules :
  # Python Modules
  py :
    mlp  : .
    echo : .

  # JavaScript Modules
  js :
    umbrella : .
    rainweb  : .

  # Go Modules
  go :
    raincore : github.com/wolfchase

nimbus-debug: 2