# RainBot on Canternet

# Server information
host : irc.canternet.org
port : 6667

# Channel Information
channels :
  - "#snowybottest"

# User information
nick     : SnowBot
realname : Rain(Neverfree) 0.7.0-alpha.2+LifeBloom
username : RainBotDevelop
modes    : +B

# Command Information
commandprefix : ","

# Modules
modules :
  # Python Modules
  py :
    mlp  : .
#    echo : .

  # JavaScript Modules
  js :
    umbrella : .
#    rainweb  : .

  # Go Modules
  go :
    raincore : github.com/wolfchase